### ISSUE TITLE
After Updating to 2026.3.0 "cannot import name 'DPType' from 'homeassistant.components.tuya.const"

### ISSUE THREAD

**Issue by Hasnaat-k** [PlusPlus-ua/ha_tuya_ble#185]
New Issue after updating. Anyone able to resolve this please?

Error occurred loading flow for integration tuya_ble: cannot import name 'DPType' from 'homeassistant.components.tuya.const' (/usr/src/homeassistant/homeassistant/components/tuya/const.py)
